name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Clean Docker System
      run: docker system prune -af
      
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        PGUSER: ${{ secrets.POSTGRES_USERNAME }}
        PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        PGDATABASE: ${{ secrets.POSTGRES_DATABASE }}
      run: |
        # Save private key to file
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        # SSH into EC2 and deploy
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST <<-EOF

          # Change to project directory
          cd time-manager

          # Pull latest changes
          git pull

          # Set environment variables
          export PGUSER=$PGUSER
          export PGPASSWORD=$PGPASSWORD
          export PGDATABASE=$PGDATABASE

          # Restart the services with forced build
          sudo docker-compose down
          sudo docker-compose up -d --build
        EOF
