name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: time_manager_dev
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      uses: sudo apt-get update && sudo apt-get install -y libncurses5 libtinfo5
      
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.12.x' # Spécifiez votre version d'Elixir
        otp-version: '24.3' # Spécifiez votre version OTP

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-
          
    - name: Install dependencies
      run: mix deps.get
      
    - name: Set up DB
      run: mix ecto.setup
      
    - name: Run tests
      run: mix test
